apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aqi-ingress
  namespace: aqi
spec:
  rules:
  - host: aqi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80