[master]
50.19.158.130 ansible_user=ubuntu ansible_ssh_private_key_file=/home/youness/.ssh/aqi-key.pem

[worker]
18.234.220.245 ansible_user=ubuntu ansible_ssh_private_key_file=/home/youness/.ssh/aqi-key.pem